---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: no-commit-to-branch
      - id: check-yaml
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.4
    hooks:
      - id: terraform-fmt
#      - id: terraform-validate
      - id: tflint
      - id: gofmt
      - id: golint
###  - repo: git://github.com/antonbabenko/pre-commit-terraform
###    rev: v1.30.0
###    hooks:
###      - id: terraform_fmt
###      - id: terraform_docs
###      - id: terraform_validate
###      - id: terraform_tflint
