---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    telemetry:
      enabled: true
  values:
    grafana:
      enabled: true
      image:
        tag: 7.0.0
    kiali:
      enabled: true
    tracing:
      enabled: true
    prometheus:
      enabled: true
      tag: v2.18.1
    pilot:
      enabled: true
      traceSampling: 1.0
    global:
      proxy:
        accessLogFile: "/dev/stdout"
