---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    telemetry:
      enabled: true
  values:
    grafana:
      enabled: true
    kiali:
      enabled: true
      dashboard:
        jaegerURL: http://jaeger-query:16686
        grafanaURL: http://grafana:3000
    tracing:
      enabled: true
    prometheus:
      enabled: false
    pilot:
      enabled: true
      traceSampling: 1.0
