name: Build
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Tag Version
        run: |
          echo "previous tag: ${{ steps.tag_version.outputs.previous_tag }}"
          echo "new version: ${{ steps.tag_version.outputs.new_version }}"
          echo "new tag: ${{ steps.tag_version.outputs.new_tag }}"
