name: Build
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        uses: Instrument/github-tag-action@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          BUMP: patch
      - name: Check Tag Version
        run: |
          echo "new tag: ${{ steps.tag_version.outputs.new_tag }}"
