name: Lint
on: [push, pull_request]

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: terraform fmt --recursive -check=true

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.29
    steps:
      - uses: actions/checkout@master
      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd $example
            terraform init -backend=false
            terraform validate
            cd -
          done

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - name: Install terraform-docs
        run: |
          # Get the download url of the latest version of terraform-docs
          tf_docs_download_url=$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -rc '.assets[] | select( .name | contains("linux-amd64")).browser_download_url')
          mkdir -p $GITHUB_WORKSPACE/bin
          curl -Lo $GITHUB_WORKSPACE/bin/terraform-docs $tf_docs_download_url
          chmod +x $GITHUB_WORKSPACE/bin/terraform-docs
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Check Docs
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --show-diff-on-failure --all-files terraform_docs

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Tag Version
        env:
          TAG_NAME: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          echo ${TAG_NAME}
